apiVersion: 1

datasources:
  # Prometheus (Spring Boot Metrics)
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: '10s'
      queryTimeout: '60s'
      httpMethod: 'POST'

  # InfluxDB (k6 Test Results)
  - name: InfluxDB-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    editable: true
    jsonData:
      version: 'Flux'
      organization: 'musicplace'
      defaultBucket: 'k6'
      tlsSkipVerify: true
    secureJsonData:
      token: 'my-super-secret-auth-token'
